
---
# Copyright 2021 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include vars of all.yaml
  include_vars:
    file: all.yaml

# we assume that the keypair is on the machine and loaded in the ssh agent
- name: Phase 1 - Create the arm graviton instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: {{ aws_keypair }}
    instance_type: {{ arm_instance_type }}
    security_group: {{ arm_security_group }}
    image: {{ arm_ami_instance }}
    region: {{ arm_region }}
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ arm_vpc }}"
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

- name: Phase 2 - Configure and build on newly build instance
  hosts: launched
  vars:
    timtim: {{ timtim }}
  tasks:
    - name: Configure the instance
      become: true
      apt:
        state: present
        update_cache: true
        pkg:
          - docker.io
          - git
          - docker-compose
          - apt-transport-https
          - curl
          - gnupg

    - name: create magma directory
      file:
        path: "{{ magma_dir }}"
        state: directory
        mode: u+rwx
        owner: "{{ usrName }}"
      become: true

    - name: download github repo
      git:
        repo: "{{ magma_repo }}"
        dest: "{{ magma_dir }}"
        version: "{{ magma_branch }}"

    - name: Build docker container
      ansible.builtin.shell:
        cmd: |
          docker login {{  }}
          docker-compose build
          docker-compose push
        chdir: {{ magma_dir }}/lte/gateway/docker/

- name: Phase 3 - Kill instances and report
  hosts: localhost
  tasks:
    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
